CREATE DATABASE IF NOT EXISTS db_kampus;
USE db_kampus;

CREATE TABLE mahasiswa (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    nim VARCHAR(20) NOT NULL,
    nama VARCHAR(100) NOT NULL,
    jurusan VARCHAR(100) NOT NULL,
    foto VARCHAR(255) NOT NULL
);